name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Install dependencies
        run: hatch env create # Create the environment with Hatch

      - name: Verify Hatch Installation
        run: hatch --version # Verify Hatch is installed

      - name: Build wheel
        run: hatch build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/databricks-*.whl
            dist/dat

      - uses: pypa/gh-action-pypi-publish@release/v1
        name: Publish package distributions to PyPI
